### ISSUE TITLE
App ID has changed

### ISSUE THREAD

**Issue by AsavarTzeth** [flathub/de.manuel_kehl.go-for-it#1]
All active development has moved to the [JMoerman fork](https://github.com/JMoerman/Go-For-It). As part of this the new project maintainer has changed the id to `com.github.jmoerman.go-for-it`.

It would be really nice if there was a way to change the application id. I remember reading about this in an issue thread somewhere, but I cannot find it at the moment. Is this actively being worked on?

If anyone has any recommendations on how to handle this in the mean time, feel free to post any suggestions.

**Comment by TingPing** [comment]
I don't think its easily doable (@ramcq)

**Comment by TingPing** [comment]
This was briefly discussed this week so its at least a known problem: https://etherpad.gnome.org/p/FlathubCall

**Comment by bbhtt** [comment]
Did something change here? JMoerman seems to be keeping it up-to-date.

If moving to a new package is needed, this one should be [EOL-ed](https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life) and the new one needs to be resubmitted with the correct app-id.
