### ISSUE TITLE
Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/de.manuel_kehl.go-for-it#2]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

**Comment by AsavarTzeth** [comment]
There are screenshots available in the [appdata](https://github.com/JMoerman/Go-For-It/blob/master/data/go-for-it.appdata.xml.in.in#L23).

I understand you are running Endless OS? I am able to reproduce this on Endless OS, but not on any other Flatpak supported distribution. Therefore I have to assume its a distribution specific issue.
